### ISSUE TITLE
Set npm package release details

### ISSUE THREAD

**Issue by hiletmis** [api3dao/logos#33]
**Acknowledgements**
- logos repo utilizes a [release CI](https://github.com/api3dao/logos/blob/main/.github/workflows/release.yml) that will update package 
- NPM package manager needs a access token to be defined on the repo 

**To-Do**
- Generate a npm access token for API3 organization (@bbenligiray)
- Add the token to Repository secrets and name it "NPM_TOKEN"  (@bbenligiray or @hiletmis)

**Comment by bbenligiray** [comment]
We have pretty critical packages published from the npm organization so we don't automate publishes. You'll just need to ask me to publish every time for now (and until you finalize everything you can publish from your personal npm account)
