### ISSUE TITLE
Cannot use package in non React Projects

### ISSUE THREAD

**Issue by Ashar2shahid** [api3dao/logos#54]
Currently this only works for react, the docs and ecosystem-website use Vue js. If possible could we have the raw SVGs also be exported and have those be imported in the react components (to avoid duplication of assets). This way both React and Vue can be supported (also vanilla js)

**Comment by hiletmis** [comment]
@Ashar2shahid package supports exporting svg files. Is the following usage not working for you?

```
import {  ChainLogoSvg, SymbolLogoSvg, ApiProviderLogoSvg } from 'beta-logos';
```
```
<img src = { ChainLogoSvg('43114') } width = { 50} height = { 50} alt = '' />
<img src = { SymbolLogoSvg('BTC') } width={50} height={50} alt='' />
<img src = { ApiProviderLogoSvg('nodary') } width={50} height={50} alt='' />
```

**Comment by hiletmis** [comment]
It may not work on vue js. You are right

**Comment by hiletmis** [comment]
React dependency removed from the package. Now you can use it on any platform using `<img>`tag

https://api3dao.github.io/logos/
