### ISSUE TITLE
Serve APi3's Logos and Icons

### ISSUE THREAD

**Issue by beejsbj** [api3dao/logos#55]
This would be a really great package if it also served API3's designed Logo's and icons

 https://github.com/api3dao/design-tokens
this repo is also being worked on, I'not sure if they are planning to serve the logos too. 

But a single package for the graphics in API3 projects would be fairly convenient.

**Comment by hiletmis** [comment]
Yes we can do that imo.

**Comment by bbenligiray** [comment]
There will be some sort of an integration at some point, just not yet

**Comment by CoCo-27** [comment]
I installed this module in my react application and imported like as following that mentioned in README file
`import { ChainLogo, SymbolLogo, ApiProviderLogo } from '@phase21/logos';
`

But I got error like 
`SyntaxError: Unexpected token '<'

This error happened while generating the page. Any console logs will be displayed in the terminal window.`

I'd appreciate it if you could help me to resolve that issue.
