### ISSUE TITLE
Reduce certain svg file sizes

### ISSUE THREAD

**Issue by hiletmis** [api3dao/logos#58]
**Acknowledgements**
- Some of the SVG files are too large

**To-Do**
- Investigate the cause of file sizes
- Reduce file sizes where available

**Comment by hiletmis** [comment]
**Details**
https://github.com/api3dao/logos/pull/59

**Comment by bbenligiray** [comment]
I think we should specify an upper limit for the file size of the logos to whoever is preparing them
